parameters:
    # Alias to values Mapbender ACL assignment machinery evaluates
    ## for fom.ldap_user_identities_provider
    ldap_user_base_dn: '%ldap.user.baseDN%'
    ldap_user_name_attribute: '%ldap.user.nameAttribute%'
    ldap_user_filter: '%ldap.user.adminFilter%'
    ## for fom.ldap_client
    ldap_host: '%ldap.host%'
    ldap_port: '%ldap.port%'
    ldap_version: '%ldap.version%'
    ldap_bind_dn: '%ldap.bind.dn%'
    ldap_bind_pwd: '%ldap.bind.pwd%'

# Fix bad parameter case baseDN (expected) vs baseDn (from bad example config in README.md)
# parameter names are now case sensitive
    ldap.user.baseDN: '%ldap.user.baseDn%'
    ldap.group.baseDN: '%ldap.group.baseDn%'
## Defaults
    ldap.group.id: cn

services:
    ldapClient:
        class: Mapbender\LDAPBundle\Component\LdapClient
        arguments:
        - '%ldap.host%' #Address to LDAPServer
        - '%ldap.port%' #Port where LDAPServer is listening
        - '%ldap.version%' #LDAP Protocol version
        - '%ldap.useSSL%'           # SSL #Use SSL
        - '%ldap.useTLS%'      # TLS 'Use TLS
        - '%ldap.bind.dn%'
        - '%ldap.bind.pwd%'
    LDAPUserProvider:
        class: Mapbender\LDAPBundle\Security\Provider\LDAPUserProvider
        arguments:
        - '@ldapClient'
        - '@mbldap.group_identities_provider'
        - '%ldap.user.baseDN%'
        - '%ldap.user.query%'
        - [ROLE_USER]
    mbldap.group_identities_provider:
        class: Mapbender\LDAPBundle\Security\Provider\LDAPGroupProvider
        arguments:
        - '@fom.ldap_client'
        - '%ldap.group.baseDN%'
        - '%ldap.group.id%'
        - '%ldap.group.adminFilter%'
        - '%ldap.group.query%'
    fom.ldap_client:
        alias: ldapClient
    fom.identities.provider:
        class: Mapbender\LDAPBundle\Security\Provider\LDAPIdentitiesProvider
        arguments:
            - '@doctrine'
            - '@fom.ldap_user_identities_provider'
            - '@mbldap.group_identities_provider'
            - '%fom.user_entity%'
