services:
    ldapClient:
        class: Mapbender\LDAPBundle\Component\LdapClient
        arguments:
        - '%ldap.host%' #Address to LDAPServer
        - '%ldap.port%' #Port where LDAPServer is listening
        - '%ldap.version%' #LDAP Protocol version
        - '%ldap.useSSL%'           # SSL #Use SSL
        - '%ldap.useTLS%'      # TLS 'Use TLS
    LDAPUserProvider:
        class: Mapbender\LDAPBundle\Security\Provider\LDAPUserProvider
        arguments:
        - '@ldapClient'
        - '%ldap.bind.dn%'
        - '%ldap.bind.pwd%'
        - '%ldap.user.baseDN%'
        - '%ldap.user.query%'
        - '%ldap.group.baseDN%'
        - '%ldap.group.query%'
        - [ROLE_USER]
        - '%ldap.group.id%'
