services:
    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
        tags:
            - ldap

    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            - host: '%ldap.host%'
            - port: '%ldap.port%'
            - encryption: '%ldap.encryption'
            - options:
                  protocol_version: '%ldap.version'
                  referrals: false

    mapbender.ldap.client:
        class: Mapbender\LDAPBundle\Security\LdapClient
        arguments:
        - '%ldap.host%'
        - '%ldap.port%'
        - '%ldap.version%'
        - '%ldap.encryption%'
        - '%ldap.bind.dn%'
        - '%ldap.bind.pwd%'

    mapbender.ldap.user_provider:
        class: Mapbender\LDAPBundle\Security\LdapUserProvider
        arguments:
        - '@mapbender.ldap.client'
        - '%ldap.user.baseDn%'
        - '%ldap.user.query%'
        - '%ldap.user.groupKey%'
        - '%ldap.group.baseDn%'
        - '%ldap.group.query%'
        - '%ldap.group.id%'
        - '%ldap.group.defaultRoles%'

    mapbender.ldap.authenticator:
        class: Mapbender\LDAPBundle\Security\MapbenderLdapAuthenticator
        arguments:
            - '@security.authenticator.form_login.secured_area'
            - '@mapbender.ldap.client'
            - '%ldap.user.baseDn%'
            - '%ldap.user.query%'

    ldap.security.subject_domain.user:
        class: Mapbender\LDAPBundle\Security\Permission\SubjectDomainLdapUser
        tags:
            - fom.security.subject_domain
        arguments:
            - '@mapbender.ldap.client'
            - '%ldap.user.baseDn%'
            - '%ldap.user.adminQuery%'
            - '%ldap.user.id%'
            - '%ldap.user.commonName%'

    ldap.security.subject_domain.group:
        class: Mapbender\LDAPBundle\Security\Permission\SubjectDomainLdapGroup
        tags:
            - fom.security.subject_domain
        arguments:
            - '@mapbender.ldap.client'
            - '%ldap.group.baseDn%'
            - '%ldap.group.adminQuery%'
            - '%ldap.group.id%'
            - '%ldap.group.commonName%'
